language: node_js
node_js:
  - 12
env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/registrations
before_script:
  - psql -c 'create database registrations;' -U postgres
  - psql -U postgres -d registrations -a -f tables.sql
services:
  - postgresql